# Generated by Django 4.0.2 on 2024-01-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('car', models.CharField(blank=True, max_length=150, null=True, verbose_name='Car')),
                ('vin', models.CharField(blank=True, max_length=150, null=True, verbose_name='Vin')),
                ('engine', models.CharField(blank=True, max_length=150, null=True, verbose_name='Engine')),
                ('year', models.CharField(blank=True, max_length=150, null=True, verbose_name='Year')),
                ('body', models.CharField(blank=True, max_length=150, null=True, verbose_name='Body')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='Country')),
                ('transmission', models.CharField(blank=True, max_length=150, null=True, verbose_name='Transmission')),
                ('fuel', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fuel')),
                ('turbo', models.BooleanField(default=False)),
                ('airbags', models.CharField(blank=True, max_length=150, null=True, verbose_name='Airbags')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
