# Generated by Django 4.0.2 on 2024-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('makes', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('sm_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
