# Generated by Django 4.0.2 on 2024-01-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
