# Generated by Django 4.0.2 on 2024-01-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_store_address_alter_store_makes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Phone Number'),
        ),
    ]
